import React, {
  useEffect,
  useMemo,
  useState,
} from 'react'

import { Activity } from 'lucide-react'

import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from 'recharts'

import {
  useAlertStore,
  useIncidentStore,
} from '../store'

import {
  useSOCStore,
} from '../store/socEngine'

import api from '../utils/api'


// =============================================================================
// COLORS
// =============================================================================

const SEV_COLOR = {
  CRITICAL: '#ff2d55',
  HIGH: '#ff9500',
  MEDIUM: '#ffd60a',
  LOW: '#00ff88',
  NORMAL: '#4a5568',
}

const STAGE_COLOR = {
  DETECTED: 'text-red-400',
  ANALYZING: 'text-yellow-400',
  CONTAINMENT: 'text-orange-400',
  RECOVERY: 'text-blue-400',
  RESOLVED: 'text-green-400',
}


// =============================================================================
// DATASET CONTEXT HELPERS
// =============================================================================

const getPrimaryOrigin = (log) => {
  const dataset = log?.dataset

  if (dataset === 'TON_IoT') {
    return log?.source_ip || 'N/A'
  }

  if (dataset === 'PhiUSIIL') {
    return log?.url || log?.domain || 'N/A'
  }

  if (dataset === 'CERT') {
    return log?.user || 'N/A'
  }

  return (
    log?.source_ip ||
    log?.url ||
    log?.domain ||
    log?.user ||
    'N/A'
  )
}

const getPrimaryTarget = (log) => {
  const dataset = log?.dataset

  if (dataset === 'TON_IoT') {
    return log?.dest_ip || 'N/A'
  }

  if (dataset === 'PhiUSIIL') {
    return log?.domain || log?.url || 'N/A'
  }

  if (dataset === 'CERT') {
    return log?.pc || 'N/A'
  }

  return (
    log?.dest_ip ||
    log?.domain ||
    log?.pc ||
    'N/A'
  )
}


// =============================================================================
// COMPONENT
// =============================================================================

export default function Monitoring() {
  // ---------------------------------------------------------------------------
  // Central SOC event stream.
  // This contains events generated by the backend MLP replay service.
  // ---------------------------------------------------------------------------

  const incidents = useSOCStore(
    (state) => state.incidents
  )

  // ---------------------------------------------------------------------------
  // Canonical AttackLog selection used by Analytics / XAI / QIGA / Response.
  // ---------------------------------------------------------------------------

  const {
    selectedAttackLogId,
    setSelectedAttackLogId,
  } = useIncidentStore()

  // ---------------------------------------------------------------------------
  // Live metrics from WebSocket.
  // ---------------------------------------------------------------------------

  const {
    liveMetrics,
  } = useAlertStore()

  const [
    chartData,
    setChartData,
  ] = useState([])

  const [
    liveDetection,
    setLiveDetection,
  ] = useState(null)


  // ===========================================================================
  // LOAD PERSISTED RISK HISTORY
  // ===========================================================================

  useEffect(() => {
    let mounted = true

    api
      .get('/dashboard/risk-history')
      .then((response) => {
        if (!mounted) {
          return
        }

        const history =
          Array.isArray(response.data)
            ? response.data
                .map((item, index) => {
                  const score = Number(
                    item?.risk ?? 0
                  )

                  return {
                    id: `history-${item?.t ?? index}-${index}`,
                    time: item?.t ?? '',
                    score: Number.isFinite(score)
                      ? score
                      : 0,
                    threats: Number(
                      item?.threats ?? 0
                    ),
                  }
                })
                .filter((item) =>
                  Number.isFinite(
                    item.score
                  )
                )
            : []

        setChartData(history)
      })
      .catch((error) => {
        console.error(
          '[Monitoring] Risk history load failed:',
          error
        )

        if (mounted) {
          setChartData([])
        }
      })

    return () => {
      mounted = false
    }
  }, [])


  // ===========================================================================
  // LIVE MLP DETECTION EVENT
  // ===========================================================================

  useEffect(() => {
    const handleMLPPrediction = (event) => {
      const data =
        event?.detail || {}

      const attackLogId =
        data.attack_log_id

      if (
        attackLogId === undefined ||
        attackLogId === null
      ) {
        return
      }

      /*
       * This is the actual frontend entry point
       * for a newly detected MLP event.
       *
       * The dataset can be:
       *
       * TON_IoT
       * PhiUSIIL
       * CERT
       *
       * No dataset is hard-coded here.
       */

      console.log(
        '[Monitoring] Live MLP detection:',
        data
      )

      setLiveDetection(data)

      /*
       * Automatically select the exact AttackLog that
       * was just detected.
       *
       * This is what allows the next pages to follow
       * the SAME event:
       *
       * Monitoring
       *    ↓
       * Analytics
       *    ↓
       * SHAP
       *    ↓
       * QIGA
       *    ↓
       * Recommendation
       */

      setSelectedAttackLogId(
        attackLogId
      )

      const score = Number(
        data.risk_score ?? 0
      )

      if (Number.isFinite(score)) {
        setChartData((previous) => [
          ...previous.slice(-29),
          {
            id: `mlp-${attackLogId}-${Date.now()}`,
            time: new Date().toLocaleTimeString(
              [],
              {
                hour12: false,
              }
            ),
            score,
            threats:
              data.prediction_label ===
                'Normal'
                ? 0
                : 1,
            dataset:
              data.dataset ?? 'Unknown',
          },
        ])
      }
    }

    window.addEventListener(
      'mlp-prediction',
      handleMLPPrediction
    )

    return () => {
      window.removeEventListener(
        'mlp-prediction',
        handleMLPPrediction
      )
    }
  }, [
    setSelectedAttackLogId,
  ])


  // ===========================================================================
  // LIVE METRICS
  // ===========================================================================

  useEffect(() => {
    if (
      liveMetrics?.risk_score ===
      undefined
    ) {
      return
    }

    const score = Number(
      liveMetrics.risk_score
    )

    if (!Number.isFinite(score)) {
      return
    }

    setChartData((previous) => [
      ...previous.slice(-29),
      {
        id: `metrics-${Date.now()}`,
        time: new Date().toLocaleTimeString(
          [],
          {
            hour12: false,
          }
        ),
        score,
      },
    ])
  }, [
    liveMetrics?.risk_score,
  ])


  // ===========================================================================
  // SELECTED INCIDENT
  // ===========================================================================

  const selectedIncident = useMemo(() => {
    if (
      selectedAttackLogId === null ||
      selectedAttackLogId === undefined
    ) {
      return null
    }

    return (
      incidents.find(
        (incident) =>
          String(
            incident.attack_log_id ??
            incident.id
          ) ===
          String(
            selectedAttackLogId
          )
      ) ?? null
    )
  }, [
    incidents,
    selectedAttackLogId,
  ])


  // ===========================================================================
  // TOP ACTIVE THREAT
  // ===========================================================================

  const topIncident = useMemo(() => {
    return (
      incidents.find(
        (incident) =>
          incident.is_threat &&
          !incident.resolved
      ) ?? null
    )
  }, [incidents])


  const displayedInsight =
    selectedIncident?.is_threat
      ? selectedIncident
      : topIncident


  // ===========================================================================
  // CURRENT RISK
  // ===========================================================================

  const currentRisk =
    liveDetection?.risk_score ??
    liveMetrics?.risk_score ??
    chartData[
      chartData.length - 1
    ]?.score ??
    0


  // ===========================================================================
  // ACTIVE THREATS
  // ===========================================================================

  const activeThreatCount =
    liveMetrics?.active_threats ??
    incidents.filter(
      (incident) =>
        incident.is_threat &&
        !incident.resolved
    ).length


  // ===========================================================================
  // RENDER
  // ===========================================================================

  return (
    <div className="p-6 space-y-6">

      {/* ================================================================== */}
      {/* HEADER                                                             */}
      {/* ================================================================== */}

      <div className="flex items-center justify-between">

        <div>

          <h1 className="text-2xl font-black text-white">
            Network Monitoring
          </h1>

          <p className="text-xs text-gray-500 font-mono mt-1">
            Real-time MLP detection · Multi-dataset telemetry · WebSocket synchronized
          </p>

        </div>

        <div className="flex items-center gap-2 text-xs font-mono px-3 py-1.5 rounded border border-cyber-cyan/50 bg-cyber-cyan/10 text-cyber-cyan">

          <span className="w-2 h-2 rounded-full bg-cyber-cyan pulse-dot" />

          SYSTEM SYNCHRONIZED

        </div>

      </div>


      {/* ================================================================== */}
      {/* CURRENT LIVE DETECTION BANNER                                     */}
      {/* ================================================================== */}

      {liveDetection && (
        <div className="cyber-card p-4 border border-cyber-cyan/30">

          <div className="flex items-center justify-between">

            <div>

              <p className="text-[10px] uppercase tracking-widest font-mono text-cyber-cyan">
                LIVE MLP DETECTION
              </p>

              <p className="text-lg font-black text-white mt-1">
                {liveDetection.prediction_label ||
                  liveDetection.attack_type ||
                  'Unknown'}
              </p>

            </div>

            <div className="text-right font-mono">

              <p className="text-xs text-gray-500">
                AttackLog
              </p>

              <p className="text-sm text-cyber-cyan font-bold">
                #{liveDetection.attack_log_id}
              </p>

            </div>

          </div>

          <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mt-4">

            <div>
              <p className="text-[10px] text-gray-600 font-mono">
                DATASET
              </p>

              <p className="text-xs text-purple-400 font-mono font-bold">
                {liveDetection.dataset ||
                  'N/A'}
              </p>
            </div>

            <div>
              <p className="text-[10px] text-gray-600 font-mono">
                CONFIDENCE
              </p>

              <p className="text-xs text-cyber-cyan font-mono font-bold">
                {Number(
                  liveDetection.confidence ??
                  0
                ).toFixed(1)}
                %
              </p>
            </div>

            <div>
              <p className="text-[10px] text-gray-600 font-mono">
                RISK
              </p>

              <p className="text-xs text-white font-mono font-bold">
                {Number(
                  liveDetection.risk_score ??
                  0
                ).toFixed(1)}
              </p>
            </div>

            <div>
              <p className="text-[10px] text-gray-600 font-mono">
                SEVERITY
              </p>

              <p
                className="text-xs font-mono font-bold"
                style={{
                  color:
                    SEV_COLOR[
                      liveDetection.severity
                    ] ||
                    '#00e5ff',
                }}
              >
                {liveDetection.severity ||
                  'N/A'}
              </p>
            </div>

            <div>
              <p className="text-[10px] text-gray-600 font-mono">
                MODEL
              </p>

              <p className="text-xs text-white font-mono">
                {liveDetection.model_version ||
                  'MLP'}
              </p>
            </div>

          </div>

        </div>
      )}


      {/* ================================================================== */}
      {/* RISK TRAJECTORY                                                    */}
      {/* ================================================================== */}

      <div className="cyber-card p-5">

        <div className="flex items-center justify-between mb-2">

          <div>

            <p className="text-xs font-mono text-gray-500 uppercase tracking-widest">
              Overall Risk Trajectory
            </p>

            <p className="text-2xl font-black font-mono text-cyber-cyan">

              {Number(
                currentRisk
              ).toFixed(1)} Risk

              <span className="text-lg text-gray-500 font-normal">
                {' '}
                | Threats: {activeThreatCount}
              </span>

            </p>

          </div>

          <Activity
            size={20}
            className="text-gray-600"
          />

        </div>

        <ResponsiveContainer
          width="100%"
          height={180}
        >

          <LineChart
            data={chartData}
          >

            <XAxis
              dataKey="time"
              tick={{
                fill: '#4a5568',
                fontSize: 10,
              }}
              interval="preserveStartEnd"
            />

            <YAxis
              domain={[
                0,
                100,
              ]}
              tick={{
                fill: '#4a5568',
                fontSize: 10,
              }}
            />

            <Tooltip
              contentStyle={{
                background:
                  '#0d1f3c',
                border:
                  '1px solid #1a3a6e',
                borderRadius: 8,
                fontSize: 11,
              }}
            />

            <Legend
              wrapperStyle={{
                fontSize: 11,
              }}
            />

            <Line
              type="monotone"
              dataKey="score"
              stroke="#00e5ff"
              dot={false}
              strokeWidth={2}
              name="MLP Risk Score"
            />

          </LineChart>

        </ResponsiveContainer>

      </div>


      {/* ================================================================== */}
      {/* LIVE INCIDENT MONITORING TABLE                                    */}
      {/* ================================================================== */}

      <div className="cyber-card p-5">

        <div className="flex items-center justify-between mb-4">

          <h3 className="text-sm font-bold text-white font-mono">
            LIVE INCIDENT MONITORING
          </h3>

          <div className="text-xs font-mono text-gray-500">
            {incidents.length} telemetry records
          </div>

        </div>

        <div className="overflow-x-auto max-h-[400px] overflow-y-auto">

          <table className="w-full text-xs font-mono">

            <thead>

              <tr className="border-b border-cyber-border text-gray-500 uppercase">

                <th className="pb-2 text-left pr-3">
                  Log ID
                </th>

                <th className="pb-2 text-left pr-3">
                  Target Asset
                </th>

                <th className="pb-2 text-left pr-3">
                  Classification
                </th>

                <th className="pb-2 text-left pr-3">
                  Risk
                </th>

                <th className="pb-2 text-left pr-3">
                  Conf
                </th>

                <th className="pb-2 text-left pr-3">
                  Source / Origin
                </th>

                <th className="pb-2 text-left pr-3">
                  Target / Context
                </th>

                <th className="pb-2 text-left pr-3">
                  Dataset
                </th>

                <th className="pb-2 text-left">
                  Status
                </th>

              </tr>

            </thead>

            <tbody>

              {incidents.map(
                (log) => {

                  const logId =
                    log.attack_log_id ??
                    log.id

                  const isSelected =
                    String(
                      selectedAttackLogId
                    ) ===
                    String(logId)

                  const isNormal =
                    log.attack_type ===
                    'Normal'

                  const severityColor =
                    isNormal
                      ? SEV_COLOR.NORMAL
                      : SEV_COLOR[
                          log.severity
                        ] ||
                        '#fff'

                  return (

                    <tr
                      key={`monitor-${logId}`}
                      onClick={() =>
                        setSelectedAttackLogId(
                          logId
                        )
                      }
                      className={`border-b border-cyber-border/30 cursor-pointer transition-colors ${
                        isSelected
                          ? 'bg-cyber-cyan/10 border-l-2 border-l-cyber-cyan'
                          : isNormal
                            ? 'bg-white/[0.01] hover:bg-white/[0.03]'
                            : 'hover:bg-white/[0.04]'
                      }`}
                    >

                      {/* LOG ID */}

                      <td className="py-3 pr-3 font-bold text-cyber-cyan">

                        #{logId}

                      </td>


                      {/* TARGET ASSET */}

                      <td className="py-3 pr-3 whitespace-nowrap">

                        <span
                          className={
                            isNormal
                              ? 'text-gray-500 block'
                              : 'text-white block'
                          }
                        >
                          {log.asset_name ||
                            'N/A'}
                        </span>

                        {log.asset_type &&
                          log.asset_type !==
                            'N/A' && (

                          <span className="text-[10px] text-gray-500">
                            {log.asset_type}
                          </span>

                        )}

                        {log.department && (

                          <span className="text-[10px] text-cyber-cyan block">
                            {log.department}
                          </span>

                        )}

                      </td>


                      {/* CLASSIFICATION */}

                      <td
                        className="py-3 pr-3 font-bold whitespace-nowrap"
                        style={{
                          color:
                            isNormal
                              ? '#a0aec0'
                              : '#fff',
                        }}
                      >

                        {isNormal ? (

                          <span className="inline-flex items-center gap-2">

                            <span>
                              NORMAL
                            </span>

                            <span className="px-1.5 py-0.5 rounded bg-gray-800 text-[9px] text-gray-400 border border-gray-700">
                              TELEMETRY
                            </span>

                          </span>

                        ) : (

                          log.attack_type ||
                          'Unknown'

                        )}

                      </td>


                      {/* RISK */}

                      <td className="py-3 pr-3">

                        <span
                          style={{
                            color:
                              severityColor,
                          }}
                        >
                          {isNormal
                            ? '--'
                            : log.risk_score !=
                              null
                              ? Math.round(
                                  Number(
                                    log.risk_score
                                  )
                                )
                              : 'N/A'}
                        </span>

                      </td>


                      {/* CONFIDENCE */}

                      <td className="py-3 pr-3 font-bold">

                        <span
                          className={
                            isNormal
                              ? 'text-gray-600'
                              : 'text-cyan-400'
                          }
                        >

                          {isNormal
                            ? '--'
                            : log.confidence !=
                              null
                              ? `${Math.round(
                                  Number(
                                    log.confidence
                                  )
                                )}%`
                              : 'N/A'}

                        </span>

                      </td>


                      {/* SOURCE / ORIGIN */}

                      <td className="py-3 pr-3 text-red-400">

                        {getPrimaryOrigin(
                          log
                        )}

                      </td>


                      {/* TARGET / CONTEXT */}

                      <td className="py-3 pr-3 text-green-400">

                        {getPrimaryTarget(
                          log
                        )}

                      </td>


                      {/* DATASET */}

                      <td className="py-3 pr-3 text-purple-400 whitespace-nowrap">

                        {log.dataset ||
                          'N/A'}

                      </td>


                      {/* STATUS */}

                      <td
                        className={`py-3 font-bold ${
                          isNormal
                            ? 'text-gray-600'
                            : STAGE_COLOR[
                                log.status
                              ] ||
                              'text-gray-400'
                        }`}
                      >

                        {isNormal
                          ? 'LOGGED'
                          : log.status ||
                            'DETECTED'}

                      </td>

                    </tr>

                  )
                }
              )}

              {incidents.length ===
                0 && (

                <tr>

                  <td
                    colSpan={9}
                    className="text-center py-8 text-gray-600"
                  >
                    Waiting for live MLP detection...
                  </td>

                </tr>

              )}

            </tbody>

          </table>

        </div>

      </div>


      {/* ================================================================== */}
      {/* SELECTED / ACTIVE THREAT CONTEXT                                  */}
      {/* ================================================================== */}

      {displayedInsight && (

        <div className="cyber-card p-4 border-l-2 border-cyber-green">

          <p className="text-xs font-mono text-cyber-green uppercase mb-1">

            MLP Detection Context ·{' '}
            {displayedInsight.dataset ||
              'Dataset'}

          </p>

          <p className="text-sm text-gray-300 font-mono italic">

            "
            {displayedInsight.attack_type}{' '}
            detected from{' '}
            {getPrimaryOrigin(
              displayedInsight
            )}{' '}
            targeting{' '}
            {displayedInsight.asset_name ||
              getPrimaryTarget(
                displayedInsight
              ) ||
              'N/A'}.

            {displayedInsight.confidence !=
            null
              ? ` AI confidence: ${Math.round(
                  Number(
                    displayedInsight.confidence
                  )
                )}%.`
              : ''}

            {displayedInsight.risk_score !=
            null
              ? ` Risk score: ${Math.round(
                  Number(
                    displayedInsight.risk_score
                  )
                )}.`
              : ''}

            {` Status: ${
              displayedInsight.status ||
              'DETECTED'
            }."`}

          </p>

        </div>

      )}


      {!displayedInsight && (

        <div className="cyber-card p-4 border-l-2 border-gray-700">

          <p className="text-xs font-mono text-gray-500 uppercase mb-1">
            Monitoring Status
          </p>

          <p className="text-sm text-gray-400 font-mono">
            Waiting for the backend MLP to detect
            the next live dataset event.
            TON_IoT, PhiUSIIL, and CERT events
            will appear here automatically.
          </p>

        </div>

      )}

    </div>
  )
}
